name: INTEGRATION
on: [ push, pull_request ]
jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Fetch connector templates
      run: npm run fetch:connector-templates
    - name: Test
      run: npm run test:integration